### ISSUE TITLE
IoT PR

### ISSUE THREAD

**Issue by Ifarra** [Komandro-CCIT/Komandro-Archive#18]
## Divisi progress

Nama divisi = IoT
Pull request terakhir = #11  
Tentang =  Pengenalan IoT

07/12/2023

**Comment by perogeremmer** [comment]
Just opened new PR:

https://github.com/Komandro-CCIT/Komandro-Archive/pull/23

**Comment by Ifarra** [comment]
Reviewed, Thank you for the contribution
